---
repository:
  description: 6502 emulator in Python
  homepage: https://dailystuff.nl/articles/2022/writing-a-6502-emulator-in-python
  topics: python, emulator, 6502
  delete_branch_on_merge: true
  has_wiki: false
#   private: false
